config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :products do
    get '/likes', to: 'c#a'
    collection do
      get '/likes_collection', to: 'c#a'
      get :my # => /products/my
    end
    member do
      get :details # => /products/:id/details?q=iPh
      # details_product_path(id: 12312, q: 'iPh')
    end

    resources :comments
    # params[:product_id], params[:id]
    # product_comment_path(product, comment)
    # product_comment_path(product_id: 123, comment_id: 3)
  end


  # resources :comments # CRUD

  # get '/products/my' => my (collection)
  # get '/products/:id/details' => details (collection)

  # resources:
  #
  # get /products => index (collection)
  # get /products/:id => show (member)
  # get /products/new => new
  # get /products/:id/edit => edit
  #
  # post /products => create
  # put(patch) /products/:id => update
  #
  # delete /products/:id => destroy


  # get '/products', to: 'products#index', as: 'products'
  # get '/products/new', to: 'products#new', as: 'new_product'
  # get '/products/:id', to: 'products#show', as: 'product'
  # post '/products', to: 'products#create', as: 'create_product'
  # delete '/products/:id', to: 'products#destroy', as: 'destroy_product'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get '/about/us/company(/:company_name)(/:department)', to: 'controller_name#action_name', as: 'about_company'
  # about_company_path(company_name: 'spalah')
  # => /about/us/company/spalah params[:department] = nil,

  # about_company_path(department: 'ruby', company_name: 'spalah')
  # => /about/us/company/spalah/ruby params[:department] = ruby,

  # match '/about/us/company(/:company_name)(/:department)', to: 'controller_name#action_name', as: 'about_company2', via: [:post, :get]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product

  validates :nick, :text, :product, presence: true
  validates :nick, length: { in: 3..12 }
  validates :text, length: { maximum: 140 }
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments


  validates :price, :name, presence: true
  validates_uniqueness_of :name

  before_validation do
    puts 'before_validation'
  end
  before_save do
    puts 'before_save'
  end
  before_create do
    puts 'before_create'
  end
  before_update do
    puts 'before_update'
  end
  before_commit do
    puts 'before_commit'
  end

  after_validation do
    puts 'after_validation'
  end
  after_save do
    puts 'after_save'
  end
  after_create do
    puts 'after_create'
  end
  after_update do
    puts 'after_update'
  end
  after_commit do
    puts 'after_commit'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :before_some_method
  after_action :after_some_method
  # around_action :around_some_method

  private

  def before_some_method
    puts 'before_action => some_method'
  end

  def after_some_method
    puts 'after_action => some_method'
  end

  def around_some_method
    puts 'around_action => some_method'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_product

  def index
    # binding.pry
    @comments = @product.comments
    @comment = @product.comments.new
  end

  def create
    # binding.pry
    @comment = @product.comments.build(comment_params)
    if @comment.save
      if request.xhr?
        render json: @comment
      else
        redirect_to product_comments_path(@product)
      end

    else
      if request.xhr?
        render json: { errors: @comment.errors.messages }
      else
        @comments = @product.comments
        render :index
      end
    end

  end

  private

  def set_product
    @product = Product.find(params[:product_id])
  end

  def comment_params
    params.require(:comment).permit(:nick, :text)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # Action for /
  # 123...
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :before_some_method, except: [:index]

  def index
    # binding.pry
    puts 'ProductsController => index'
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new
    @product.price = params[:product][:price]
    @product.name = params[:product][:name]
    @product.save

    redirect_to products_path
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    if request.xhr?
      head :no_content
    else
      redirect_to products_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def price_format(value)
    "#{value} $"
  end
end

app/views/comments/index.html.erb
<ul id="comments-list">
  <% @comments.each do |com| %>
    <% next unless com.persisted? %>
  <li>
    <%= com.nick %> :
    <%= com.text %>
  </li>
  <% end %>
</ul>


<ul class="comment-errors">
  <% if @comment.errors.present? %>
    <% @comment.errors.messages.each do |field, messages| %>
    <li><%= field %>: <%= messages.join('; ') %></li>
    <% end %>
  <% end %>
</ul>


<%= form_for [@product, @comment], remote: true do |f| %>
  <%= f.text_field :nick, placeholder: 'Nick' %>
  <br>
  <br>
  <%= f.text_area :text, placeholder: 'Message' %>
  <br>
  <%= f.submit %>
<% end %>
<br>
<a href="" class="test">CLICK ME!</a>
<br>
<span class="click-result">0</span>

app/views/home/index.html.erb
<h1>Welcome to E-Shop</h1>
<%= link_to products_path do %>
  <span>Products list</span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  </head>

  <body>
  <h1>
    <%= link_to 'E-Shop', root_path %>
  </h1>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<ul>
  <% @products.each do |product| %>
    <li>
      <%= link_to product.name, product_path(id: product.id) %>:
      <%= price_format(product.price) %>
      |
      <%= link_to 'Delete', product_path(product), method: :delete %>
      <!--<a class="delete-product" href="<%= product_path(product) %>">Delete</a>-->
    </li>
  <% end %>
</ul>
<%= link_to 'New', new_product_path %>

app/views/products/new.html.erb
<%= form_for @product do |f| %>
  <%= f.text_field :price, placeholder: 'Price' %>
  <%= f.text_field :name, placeholder: 'Name' %>
  <%= f.submit 'Create' %>
<% end %>

app/views/products/show.html.erb
<h3><%= @product.name %>: <%= @product.price %> $</h3>

<%= link_to 'Show comments', product_comments_path(@product) %>